# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='course_app.Course'),
            preserve_default=False,
        ),
    ]
