# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170125_1739'),
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.User'),
            preserve_default=False,
        ),
    ]
