# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_confirm_pw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(max_length=256),
        ),
    ]
